services:
  php:
    build: .
    container_name: laravel_php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks: [app-net]

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [php]
    networks: [app-net]

networks:
  app-net:
    driver: bridge
